# Generated by Django 5.2.16 on 2026-07-11 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('mapping_id', models.CharField(blank=True, max_length=200)),
                ('pack_version', models.CharField(blank=True, max_length=100)),
                ('source_repo', models.CharField(blank=True, max_length=300)),
                ('source_commit', models.CharField(blank=True, max_length=100)),
                ('content_digest', models.CharField(max_length=128)),
                ('framework_name', models.CharField(blank=True, max_length=100)),
                ('framework_release', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['scenario', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer'), ('stakeholder', 'Stakeholder'), ('administrator', 'Administrator')], default='reviewer', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(related_name='projects', through='workbench.Membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workbench.project'),
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=20)),
                ('object_stable_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='workbench.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(choices=[('tactic', 'Tactic'), ('step', 'Step'), ('technique', 'Technique'), ('evidence', 'Evidence')], max_length=20)),
                ('object_stable_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('accepted', 'Accepted'), ('needs-change', 'Needs change'), ('resolved', 'Resolved')], default='unreviewed', max_length=20)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_updates', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_states', to='workbench.revision')),
            ],
            options={
                'ordering': ['revision', 'object_type', 'object_stable_id'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='workbench.revision')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['revision', 'evidence_id'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(choices=[('tactic', 'Tactic'), ('step', 'Step'), ('technique', 'Technique'), ('evidence', 'Evidence')], max_length=20)),
                ('object_stable_id', models.CharField(max_length=100)),
                ('decision', models.CharField(choices=[('accept', 'Accept'), ('needs-change', 'Needs change'), ('resolve', 'Resolve'), ('reopen', 'Reopen')], max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='workbench.revision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(choices=[('tactic', 'Tactic'), ('step', 'Step'), ('technique', 'Technique'), ('evidence', 'Evidence')], max_length=20)),
                ('object_stable_id', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='workbench.comment')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workbench.revision')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='workbench.project')),
            ],
            options={
                'ordering': ['project', 'name'],
            },
        ),
        migrations.AddField(
            model_name='revision',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='workbench.scenario'),
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_step', models.CharField(max_length=16)),
                ('behavior_specification', models.CharField(blank=True, max_length=200)),
                ('tier', models.CharField(blank=True, max_length=32)),
                ('surface', models.CharField(blank=True, max_length=100)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('objective', models.TextField(blank=True)),
                ('flag_outcome', models.CharField(blank=True, max_length=100)),
                ('justification', models.TextField(blank=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workbench.revision')),
            ],
            options={
                'ordering': ['revision', 'path_step'],
            },
        ),
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tactic_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tactics', to='workbench.revision')),
            ],
            options={
                'ordering': ['revision', 'tactic_id'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('surface', models.CharField(blank=True, max_length=100)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('coverage_status', models.CharField(blank=True, max_length=50)),
                ('planned_action', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techniques', to='workbench.evidence')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='workbench.revision')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techniques', to='workbench.step')),
                ('tactics', models.ManyToManyField(blank=True, related_name='techniques', to='workbench.tactic')),
            ],
            options={
                'ordering': ['revision', 'technique_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_member'),
        ),
        migrations.AddConstraint(
            model_name='reviewstate',
            constraint=models.UniqueConstraint(fields=('revision', 'object_type', 'object_stable_id'), name='unique_review_state'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(fields=('revision', 'evidence_id'), name='unique_evidence'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='unique_scenario_slug'),
        ),
        migrations.AddConstraint(
            model_name='revision',
            constraint=models.UniqueConstraint(fields=('scenario', 'content_digest'), name='unique_revision_digest'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('revision', 'path_step'), name='unique_step'),
        ),
        migrations.AddConstraint(
            model_name='tactic',
            constraint=models.UniqueConstraint(fields=('revision', 'tactic_id'), name='unique_tactic'),
        ),
        migrations.AddConstraint(
            model_name='technique',
            constraint=models.UniqueConstraint(fields=('revision', 'technique_id'), name='unique_technique'),
        ),
    ]
