# Generated by Django 5.2.16 on 2026-07-12 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0003_drop_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_type',
            field=models.CharField(choices=[('tactic', 'Tactic'), ('step', 'Step'), ('technique', 'Technique'), ('evidence', 'Evidence'), ('challenge', 'Challenge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='decision',
            name='object_type',
            field=models.CharField(choices=[('tactic', 'Tactic'), ('step', 'Step'), ('technique', 'Technique'), ('evidence', 'Evidence'), ('challenge', 'Challenge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewstate',
            name='object_type',
            field=models.CharField(choices=[('tactic', 'Tactic'), ('step', 'Step'), ('technique', 'Technique'), ('evidence', 'Evidence'), ('challenge', 'Challenge')], max_length=20),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_id', models.CharField(max_length=100)),
                ('outcome_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('question', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('points', models.PositiveIntegerField(blank=True, null=True)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('implemented', models.BooleanField(default=False)),
                ('runtime_entrypoint', models.CharField(blank=True, max_length=200)),
                ('source_path', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='workbench.revision')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='workbench.step')),
                ('techniques', models.ManyToManyField(blank=True, related_name='challenges', to='workbench.technique')),
            ],
            options={
                'ordering': ['revision', 'flag_id'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeEvidenceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_key', models.CharField(max_length=100)),
                ('predicate', models.TextField(blank=True)),
                ('source_path', models.CharField(blank=True, max_length=300)),
                ('event_id', models.CharField(blank=True, max_length=100)),
                ('event_kind', models.CharField(blank=True, max_length=100)),
                ('source_service', models.CharField(blank=True, max_length=100)),
                ('source_asset', models.CharField(blank=True, max_length=100)),
                ('freshness_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('reset_owner', models.CharField(blank=True, max_length=100)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('proof_fields', models.JSONField(blank=True, default=list)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_requirements', to='workbench.challenge')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_requirements', to='workbench.evidence')),
            ],
            options={
                'ordering': ['challenge', 'evidence_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.UniqueConstraint(fields=('revision', 'flag_id'), name='unique_challenge'),
        ),
        migrations.AddConstraint(
            model_name='challengeevidencerequirement',
            constraint=models.UniqueConstraint(fields=('challenge', 'evidence_key'), name='unique_challenge_evidence'),
        ),
    ]
