# Generated by Django 5.2.16 on 2026-07-11 21:46

import aces_scenario_workbench.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('workbench', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('author', 'Author'), ('reviewer', 'Reviewer'), ('stakeholder', 'Stakeholder'), ('administrator', 'Administrator')], default='reviewer', max_length=20)),
                ('token', models.CharField(default=aces_scenario_workbench.accounts.models._default_invitation_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workbench.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
